### ISSUE TITLE
Check for scheme and X-Forwarded-For

### ISSUE THREAD

**Issue by joscdk** [nodes-vapor/gatekeeper#1]
When checking for SSL, it's never a good idea to look for the uri scheme.

Usually proxy servers will send the `X-Forwarded-Proto` header

So a better solution is first to check the scheme as now, if that's `http`, then check if `X-Forwarded-Proto` is `https`

**Comment by Casperhr** [comment]
`request.headers["X-Forwarded-Proto"]`

**Comment by steffendsommer** [comment]
Closing due to #5
