### ISSUE TITLE
When support vapor 3?

### ISSUE THREAD

**Issue by PublicWorld** [nodes-vapor/gatekeeper#14]
···

**Comment by steffendsommer** [comment]
We're currently in the process of migrating our packages to Vapor 3 and you can follow our progress here https://github.com/nodes-vapor/readme/projects/2

Gatekeeper is currently not in progress, but I expect it to be picked up as soon as we have moved more tickets to "Done". Contributions are also very much appreciated.

**Comment by PublicWorld** [comment]
@steffendsommer 

I found a Guardian ( https://github.com/Jinxiansen/Guardian ), it appears to be the gatekeeper of vapor 3 versions.

**Comment by cweinberger** [comment]
FYI: we have update Gatekeeper for vapor-3 now.
