### ISSUE TITLE
Gatekeeper fails in testing

### ISSUE THREAD

**Issue by foffer** [nodes-vapor/gatekeeper#17]
After adding Gatekeep to my Vapor app, my test harness fails due to the framework checking if there is a hostname on this line https://github.com/nodes-vapor/gatekeeper/blob/master/Sources/Gatekeeper/Gatekeeper.swift#L20 if there is a hostname attached to the request. XCTest doesn't seem to attach this to any request and thus tests won't pass. I don't seem to be able to add a hostname manually, so maybe a check to see if the env is testing and then manually set the hostname to `localhost`? I'd be happy to file a pull request if this would be a satisfactory solution

**Comment by siemensikkema** [comment]
@foffer I assume you have some control over the requests your using in your tests. If that is indeed the case, you can add a fake hostname like so:
```swift
var httpRequest = HTTPRequest(method: .GET, url: "http://www.example.com")
httpRequest.headers.add(name: .forwarded, value: "by=BY;for=FOR")
httpRequest.remotePeer.hostname // this resolves to "FOR" as specified above in the header value
let request = Request(http: httpRequest, using: container)
```

Let me know if that resolves your issue 🙂

**Comment by foffer** [comment]
If I do as above and log req.http.remotePeer.hostname in my test it correctly returns the hostname, but if i log it in Gatekeeper.swift the hostname is still empty?

**Comment by foffer** [comment]
Thanks, that fixed it!
